# SPDX-FileCopyrightText: Copyright (C) 2026 KU Leuven (MICAS). All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path

import aie.utils as aie_utils

from iron.common import DesignGenerator, from_spec
from iron.common.kernels import kernels_dir
from iron.common.image import OperatorSequence


def _stream_group(seq_len, embedding_dim, hidden_dim, k, group_index, context):
    """One stream-dse design, as an operator declared from the exported graph.

    ``k`` is how many fused groups the block is split into and ``group_index``
    which of them this is, in the order
    :data:`~iron.operators.swiglu_prefill_stream.stream_design.GROUP_LAYERS`
    lists them. The buffers' shapes and order come from the workload, which is
    also the order the generated design takes its arguments in; the design
    itself is the exported text, so the class is built at run time
    (:func:`~iron.common.declare.from_spec`) rather than declared.
    """
    from iron.operators.swiglu_prefill_stream import stream_design

    dims = (seq_len, embedding_dim, hidden_dim)
    shapes = stream_design.workload_for(*dims).shapes
    inputs, outputs = stream_design.group_ports(*dims, k=k)[group_index]
    npu = aie_utils.get_current_device().resolve().name

    def generator(self, image="elf"):
        """The exported design, loaded from its module rather than derived."""
        return DesignGenerator(
            source_path=Path(stream_design.__file__),
            fn_name="load_group",
            kwargs={
                "group_index": group_index,
                "k": k,
                "seq_len": seq_len,
                "embedding_dim": embedding_dim,
                "hidden_dim": hidden_dim,
                "npu": npu,
                "kernels_dir": kernels_dir(),
            },
        )

    cls = from_spec(
        "SwiGLUStreamGroup",
        inputs={name: shapes[name] for name in inputs},
        outputs={name: shapes[name] for name in outputs},
        # Groups whose generated design is byte-identical share it.
        key=stream_design.group_digest(
            group_index,
            k=k,
            seq_len=seq_len,
            embedding_dim=embedding_dim,
            hidden_dim=hidden_dim,
            npu=npu,
        ),
        params={
            "seq_len": seq_len,
            "embedding_dim": embedding_dim,
            "hidden_dim": hidden_dim,
            "k": k,
            "group_index": group_index,
        },
        generator=generator,
    )
    return cls(context=context)


def _wiring(seq_len, embedding_dim, hidden_dim, k):
    """Each group's arguments, and the operator's own inputs and outputs.

    A group's arguments are the tensors it consumes and produces, in the order the
    exported graph uses them. The operator's own arguments are what no group
    produces and what none consumes. Imported lazily, so only building the operator
    needs stream-dse, not importing it.
    """
    from iron.operators.swiglu_prefill_stream.stream_design import group_ports

    boundaries = group_ports(seq_len, embedding_dim, hidden_dim, k)
    produced = {name for _, outputs in boundaries for name in outputs}
    consumed = {name for inputs, _ in boundaries for name in inputs}
    ports = [inputs + outputs for inputs, outputs in boundaries]
    external_inputs = dict.fromkeys(
        name for inputs, _ in boundaries for name in inputs if name not in produced
    )
    external_outputs = dict.fromkeys(
        name for _, outputs in boundaries for name in outputs if name not in consumed
    )
    return ports, list(external_inputs), list(external_outputs)


class SwiGLUPrefillStream(OperatorSequence):
    """SwiGLU-prefill block generated by stream-dse and deployed as one full ELF.

    ``k`` is how many fused groups the block is split into: 1 keeps the whole block
    on the array at once, 2 splits after the elementwise multiply, and 5 runs layer
    by layer, each layer taking the whole array in turn as
    :mod:`iron.operators.swiglu_prefill` does. The split is decided by the mapping's
    fused groups, and the external buffers are the same either way.

    Runtime buffers (``get_callable().get_buffer(name)``) are named by the reference
    module: ``input``, ``w_gate``, ``w_up``, ``w_down``, ``output``. Building
    requires ``stream-dse`` (``pip install stream-dse`` + ``stream-setup-aie``);
    importing this module does not.
    """

    def __init__(
        self, seq_len, embedding_dim, hidden_dim, k=1, context=None, share_designs=True
    ):
        from iron.operators.swiglu_prefill_stream.stream_design import trace_size

        ports, inputs, outputs = _wiring(seq_len, embedding_dim, hidden_dim, k)
        groups = [
            _stream_group(seq_len, embedding_dim, hidden_dim, k, index, context)
            for index in range(len(ports))
        ]
        super().__init__(
            name=f"swiglu_prefill_stream_k{k}_m{seq_len}_e{embedding_dim}_h{hidden_dim}",
            runlist=[
                (group, *group_ports) for group, group_ports in zip(groups, ports)
            ],
            input_args=inputs,
            output_args=outputs,
            trace_size=trace_size(),
            share_designs=share_designs,
            context=context,
        )
