#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (C) 2026 KU Leuven (MICAS). All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import pytest
import torch
from aie.utils.benchmark import run_iters

from iron.common.tracing import dump_traces

# The design is generated by stream-dse at compile() time. stream-dse is an
# optional dependency (see requirements_stream.txt) absent from the default CI
# image, so skip this whole module when it is unavailable.
pytest.importorskip(
    "stream", reason="stream-dse not installed (see requirements_stream.txt)"
)

# stream-dse's codegen emits `!aie.objectfifosubview`, which mlir-aie removed in
# Xilinx/mlir-aie#3553. Every wheel carrying the trace slice API this branch needs is
# newer than that removal. Revert this commit once a stream-dse release targets a
# post-#3553 mlir-aie.
pytest.skip(
    "stream-dse codegen does not parse against the pinned mlir-aie",
    allow_module_level=True,
)

from iron.common.harness import record_metric, verify_buffer  # noqa: E402

# The operator's design is generated from this module; the values it is checked
# against come from swiglu_decode's reference, which it shares.
from iron.operators.swiglu_decode.reference import (  # noqa: E402
    generate_golden_reference,
)
from iron.operators.swiglu_prefill_stream.op import SwiGLUPrefillStream  # noqa: E402
from iron.operators.swiglu_prefill_stream.reference import (  # noqa: E402
    INPUT,
    OUTPUT,
    WEIGHTS,
)

# The MILP-feasible shape on the whole-array Strix (npu2) target.
SEQ_LEN, EMBEDDING_DIM, HIDDEN_DIM = 256, 512, 2048

# Fused groups to deploy the block as: one design, a front end plus the down
# projection, or one design per layer.
FUSION_GROUPS = [1, 2, 5]

# Timed dispatches per test; the reported latency is the fastest of them.
TIMED_RUNS = 3


def _staged(operator, golden_ref):
    """A callable with its inputs staged.

    Inputs are named by the golden reference, and the design consumes the weights in
    their natural (K, N) layout.
    """
    run = operator.get_callable()
    for name in (INPUT, *WEIGHTS):
        buffer = run.get_buffer(name)
        buffer.torch_view()[:] = golden_ref[name].to(torch.bfloat16).flatten()
        buffer.to("npu")
    return run


@pytest.mark.supported_devices("npu2")
@pytest.mark.parametrize("k", FUSION_GROUPS)
def test_swiglu_prefill_stream(k, npu_runtime):
    golden_ref = generate_golden_reference(M=SEQ_LEN, K=EMBEDDING_DIM, N=HIDDEN_DIM)
    operator = SwiGLUPrefillStream(
        seq_len=SEQ_LEN,
        embedding_dim=EMBEDDING_DIM,
        hidden_dim=HIDDEN_DIM,
        k=k,
    )
    operator.compile()

    # The whole block is computed in bf16, so rounding accumulates and reorders
    # across the chain and the K=hidden_dim down-projection sum (near-cancellation
    # amplifies relative error): ~20% of elements drift past the 8% bound, so allow
    # up to 25%. Tolerances are local to this test.
    run = _staged(operator, golden_ref)
    run()
    dump_traces(run, f"swiglu_k{k}")
    output = run.get_buffer(OUTPUT).to_torch().reshape((SEQ_LEN, EMBEDDING_DIM))
    errors = verify_buffer(
        output,
        OUTPUT,
        golden_ref[
            OUTPUT
        ],  # pyright: ignore[reportArgumentType]  # a bf16 torch tensor
        rel_tol=0.08,
        abs_tol=0.7,
        max_error_rate=0.25,
    )
    assert not errors, f"Test failed with errors: {errors}"

    # The first dispatch on a callable pays for its hardware context, so time the
    # ones after it.
    latency = run_iters(run, iters=TIMED_RUNS).e2e
    elapsed_us = latency.min_us
    total_bytes = 4 * SEQ_LEN * EMBEDDING_DIM  # bf16 in + out
    print(
        f"Latency min/mean/max (us): {elapsed_us:.2f} / "
        f"{latency.avg_us:.2f} / {latency.max_us:.2f}"
    )
    record_metric("Latency", elapsed_us)
    record_metric("Bandwidth", total_bytes / (elapsed_us * 1e-6) / 1e9)
